---
# Additional application node prefixes
prefixes:
  - slurm

  # Defaut
  - uan
  - gn
  - ln

# HSM Subroles
prefix_hsm_subroles:
  slurm: SLURM

  dvs: "~~FIXME~~"

  uan:	UAN
  ln:	UAN
  gn:	Gateway

# Application Node alias
aliases:
  x3000c0s15b0n0: ["uan01"]
  x3000c0s16b0n0: ["uan02"]

  # NEw stuff
  x3001c0s16b0n0: ["uan03"]
